### ISSUE TITLE
Create a "saves" folder if one doesn't exist when loading/saving

### ISSUE THREAD

**Issue by SilentMrDave** [2105-may24-devops/davidr-project0#2]
The save and load functions currently don't check if the saves folder (in the project root) exists. Add code to create the folder in both these cases. If loading also check if the "save1.json" file exists. If it does not then raise an exception.

**Comment by davidpearl20** [comment]
could you let me know anything I need to install to run your program properly? I installed blessed and jsonpickle but it's hard to understand the user interface / gameflow in current form. That being said, could you explain further how or when the saves folder is being accessed, and how to simulate that at runtime?

**Comment by SilentMrDave** [comment]
That should be everything you need to run it. Inside fileio.py is where the issue exists. I want both the load and save functions to create a "saves" folder if the folder doesn't exist when called.
